BusWaiting/urls.py
from django.conf.urls import url ,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('buswait.urls'), name='buswait'),
    url(r'^admin/', admin.site.urls),
]

buswait/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import TemplateView

from . import views

app_name = 'buswait'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^busStop/$', views.busStopDetail, name='busStopDetail'),
    url(r'^bus/$', views.busDetail, name='busDetail'),
    url(r'^about/$', TemplateView.as_view(template_name='buswait/about.html'), name='about'),
    url(r'^report/(?P<busStop_id>[0-9]+)/$', views.report_bus, name='report_bus'),
	url(r'^register/$', views.register, name='register'),
	url('^', include('django.contrib.auth.urls')),
	url(r'^logout_success/$', views.logout_success, name='logout_success'),
	url(r'^set_favorite_busstop/(?P<busstop>[^\n]+)/$', 
	views.set_favorite_busstop, name='set_favorite_busstop'),
	url(r'^set_favorite_bus/(?P<bus_id>[0-9]+)/$', views.set_favorite_bus, name='set_favorite_bus'),
]

buswait/models.py
from django.db import models
import datetime
from itertools import chain
from django.utils import timezone 
from django.contrib.auth.models import User

# Create your models here.
class Route(models.Model):
	bus_number = models.CharField(max_length=10)
    
	def __str__(self):
		return self.bus_number
    
class BusStop(models.Model):
	route = models.ForeignKey(Route, on_delete=models.CASCADE)
	name = models.CharField(max_length=30)
	time = models.DateTimeField('time', blank=True, null=True)
    
	def __str__(self):
		return self.name
    
	def get_previous(self):
		previous = self.route.busstop_set.filter(
            id__lte=self.id).order_by('-id')[:3]
		return previous
    
	def is_today(self):
		try:
			return timezone.now().date() == self.time.date()
		except:
			return False
			
	def busFilter(self, filter):
		nexts = self.route.busstop_set.filter(id__gt=self.id)
		for nextBusStop in nexts:
			if (nextBusStop.name == filter):
				return True
		return False
		
class FavoriteBusStop(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	busstop = models.CharField(max_length=30)
	
class FavoriteBus(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	bus = models.ForeignKey(Route, on_delete=models.CASCADE)

buswait/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.urls import reverse
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from buswait.models import *

def register(request):
	if request.method == 'POST':
		data = request.POST
		form = UserCreationForm(data)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=password)
			user.save()
			return redirect(reverse('buswait:login'))
	else:
		form = UserCreationForm()	
	return render(request, 'registration/register.html', {'form': form})
		
def logout_success(request):
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def index(request):
	busStop_set = BusStop.objects.values('name').distinct()
	bus_set = Route.objects.values('bus_number').distinct()
	data = {'busStop_set': busStop_set, 'bus_set': bus_set}
	if request.user.is_authenticated:
		user = request.user
		favorite_busstop = FavoriteBusStop.objects.filter(user=user)
		favorite_bus = FavoriteBus.objects.filter(user=user)
		data['favorite_busstop'] = favorite_busstop
		data['favorite_bus'] = favorite_bus
	return render(request, 'buswait/index.html', data)

	
def busStopDetail(request):
	# create default context
	busStop_datalist = BusStop.objects.values('name').distinct()
	busStopName = ''
	busStop_set = set()
	filter = ''
	favorite = False
	context = {	'busStopName': busStopName, 'busStop_set': busStop_set, 
				'filter': filter, 'busStop_datalist': busStop_datalist,
				'favorite': favorite}
	try:
		busStopName = request.GET['busStop']
		filter = request.GET['filter']
		busStop_set = BusStop.objects.filter(name=busStopName)
		
		if (filter != ""):	# check filter
			temp = []
			for busStop in busStop_set:
				if (busStop.busFilter(filter) == True):
					temp.append(busStop)
			busStop_set = temp	
			
		context['busStopName'] = busStopName
		context['busStop_set'] = busStop_set
		context['filter'] = filter
		context['busStop_datalist'] = busStop_datalist
		
		if request.user.is_authenticated:	# check favorite
			user = request.user
			favorite = FavoriteBusStop.objects.filter(user=user, busstop=busStopName)
			context['favorite'] = favorite.exists()
	except:
		pass
		
	return render(request, 'buswait/busStopDetail.html', context)


def busDetail(request):
	busNumber = ''
	busStop_set = set()
	favorite = False
	context = {'busNumber': busNumber, 'busStop_set': busStop_set,
	'favorite': favorite}
	
	try:
		busNumber = request.GET['busNumber']
		bus = Route.objects.filter(bus_number=busNumber).first()
		busStop_set = bus.busstop_set.all()
		context['busNumber'] = bus
		context['busStop_set'] = busStop_set
		if request.user.is_authenticated:	# check favorite
			user = request.user
			favorite = FavoriteBus.objects.filter(user=user, bus=bus)
			context['favorite'] = favorite.exists()
	except:
		pass

	return render(request, 'buswait/busDetail.html', context)


def report_bus(request, busStop_id):
	busStop = get_object_or_404(BusStop, id=busStop_id)
	busStop.time = timezone.now()
	busStop.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def set_favorite_busstop(request, busstop):
	user = request.user
	favorite = FavoriteBusStop.objects.filter(user=user, busstop=busstop)
	if favorite.exists():
		favorite.delete()
	else:
		favorite = FavoriteBusStop(user=user, busstop=busstop)
		favorite.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
	
@login_required
def set_favorite_bus(request, bus_id):
	user = request.user
	bus = get_object_or_404(Route, id=bus_id)
	favorite = FavoriteBus.objects.filter(user=user, bus=bus)
	if favorite.exists():
		favorite.delete()
	else:
		favorite = FavoriteBus(user=user, bus=bus)
		favorite.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
	
def create_object():
	r203 = Route(bus_number="203")
	r203.save()
	r203.busstop_set.create(name="ท่าอิฐ")
	r203.busstop_set.create(name="ท่าน้ำนนท์บุรี")
	r203.busstop_set.create(name="โรงเรียนสตรีนนทบุรี")
	r203.busstop_set.create(name="มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ")
	r203.busstop_set.create(name="โรงพยาบาลยันฮี")
	r203.busstop_set.create(name="สนามหลวง")
	r203.save()
	r97 = Route(bus_number="97")
	r97.save()
	r97.busstop_set.create(name="กระทรวงสาธารณสุข")
	r97.busstop_set.create(name="ท่าน้ำนนท์บุรี")
	r97.busstop_set.create(name="โรงเรียนสตรีนนทบุรี")
	r97.busstop_set.create(name="มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ")
	r97.busstop_set.create(name="อนุสาวรีย์ชัยสมรภูมิ")
	r97.busstop_set.create(name="โรงพยาบาลสงฆ์")
	r97.save()

buswait/templates/buswait/about.html
{% extends 'buswait/base.html' %}
{% block title %}About-{% endblock %}
{% block header %}About{% endblock %}
{% block detail %}
    App สำหรับบอกเวลาที่รถประจำทางผ่านป้าย เพื่อให้สามารถคาดการณ์เวลาที่ใช้รอรถได้
    <h1> Feture </h1>
    <li> สามารถ report เวลามีรถผ่านเพื่อให้ผู้ใช้คนอื่นทราบ </li>
    <li> ค้นหาป้ายที่ต้องการได้อย่างแม่นยำ </li>
    <li> ค้นหาได้ทั้งป้ายและรถประจำทาง </li>
    <li> รีเช็ตข้อมูลทุกวันเพื่อป้องกันการสับสน </li>
    <a href={% url 'buswait:index' %}>back</a>
{% endblock %}

buswait/templates/buswait/base.html
<!DOCTYPE html>
<html lang="en">
<html>
	<head>
    <title>{% block title %}
    {% endblock %} BusWaiting App</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="/static/theme.css" rel="stylesheet">
	</head>
    <body>
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href={% url 'buswait:index' %}>BusWaiting</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href={% url 'buswait:about' %}>About</a></li>
      <!-- <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
	{% if user.is_authenticated %}
		<li><a href="#"><span class="glyphicon glyphicon-user"></span> {{user.username}}</a></li>
		<li><a href={% url 'buswait:logout' %}><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
	{% else %}
		<li><a href={% url 'buswait:register' %}><span class="glyphicon glyphicon-user"></span> Register</a></li>
		<li><a href={% url 'buswait:login' %}><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
	{% endif %}
    </ul>
  </div>
</nav>
        <h1>{% block header %}{% endblock %}</h1>
        {% block detail %}{% endblock %}
        {% block input %}{% endblock %}
        {% block table %}{% endblock %}
    </body>
</html>

buswait/templates/buswait/busDetail.html
{% extends 'buswait/base.html' %}

{% block title %}{{ busNumber }}-{% endblock %}

{% block header %}
{{ busNumber }}
	{% if user.is_authenticated and busStop_set %}
		<span>
		{% if favorite %}
			<a href={% url 'buswait:set_favorite_bus' busNumber.id %} title="Remove Favorite"><span class="glyphicon glyphicon-star"></span></a>
		{% else %}
			<a href={% url 'buswait:set_favorite_bus' busNumber.id %} title="Add Favorite"><span class="glyphicon glyphicon-star-empty"></a>
		{% endif %}
		</span>
	{% endif %}
{% endblock %}

{% block table %}
	<h2> {{busStop_set.first}} - {{busStop_set.last}}</h2>
    {% if busStop_set %}
    <div class="datagrid">
        <table align="center" id="busStop_table">
            <tr>
                <th> Bus Stop </th>
                <th width="10%"> time </th>
                <th width="10%"> report </th>
            </tr>
            {% for busStop in busStop_set %}
                <tr>
                    <td class="hyperlink"
                        onclick="location.href='{% url 'buswait:busStopDetail' %}?busStop={{busStop.name}}&filter='"> {{busStop.name}} </td>
                    {% if busStop.is_today %}
                        <td> {{busStop.time|date:"H:i"}} </td>
                    {% else %} 
                        <td> - </td>
                    {% endif %}
                    <td> <a href={% url 'buswait:report_bus' busStop.id %} > report </a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
    {% endif %}
    <a class="button" href={% url 'buswait:index' %}>back</a>
{% endblock %}

buswait/templates/buswait/busStopDetail.html
{% extends 'buswait/base.html' %}

{% block title %}{{ busStopName }}-{% endblock %}

{% block header %}
{{ busStopName }}
{% if user.is_authenticated and busStop_set %}
		<span>
		{% if favorite %}
			<a href={% url 'buswait:set_favorite_busstop' busStopName %} title="Remove Favorite"><span class="glyphicon glyphicon-star"></span></a>
		{% else %}
			<a href={% url 'buswait:set_favorite_busstop' busStopName %} title="Add Favorite"><span class="glyphicon glyphicon-star-empty"></a>
		{% endif %}
		</span>
	{% endif %}
{% endblock %}

{% block table %}
	<form method="get">
	<input type="hidden" name="busStop" value={{busStopName}}>
	{% if filter %}
		<h2> to {{filter}} </h2>
	{% endif %}
	Filter: <input type="text" id="filter" name="filter" list="filter">
	<datalist id="filter">
		{% if busStop_datalist %}
			{% for busstop in busStop_datalist %}
				<option value={{busstop.name}}>
			{% endfor %}
		{% endif %}
	</datalist>
	<input type="submit" value="Apply">
	<a class="button" onclick="location.href='' type="button"> Clear </a>
	</form>
    {% if busStop_set %}
    <div class="datagrid">
        <table align="center" id="bus_table">
            <tr>
                <th width="10%">    Bus <br> Number     </th>
				<th width="20%">    Direction     		</th>
                <th>                Location            </th>
                <th width="10%">    Time                </th>
                <th width="10%">    Report              </th>
            </tr>
            {% for busStop in busStop_set %}
                {% for location in busStop.get_previous %}
                
                <tr id={{busStop.route}}>
                    
                    {% if forloop.counter == 1 %}
                        <td rowspan={{busStop.get_previous|length}} 
                            class="hyperlink"
                            onclick="location.href='{% url 'buswait:busDetail' %}?busNumber={{busStop.route}}'">
                        {{busStop.route}} </td>
						<td rowspan={{busStop.get_previous|length}} >
                        {{busStop.route.busstop_set.last}} </td>
                    {% endif %}
                    
                        <td id={{location.name}}> {{location.name}} </td>
                        
                        <td id={{location.name}}_time>
                    {% if location.is_today %}
                        {{location.time|date:"H:i"}} 
                    {% else %} 
                        - 
                    {% endif %}
                        </td>
                        
                    {% if forloop.counter == 1 %}
                        <td rowspan={{busStop.get_previous|length}}> 
                        <a class="button" href={% url 'buswait:report_bus' busStop.id %} > report </a></td>
                    {% endif %}
            
                </tr>
                {% endfor %}
            {% endfor %}
            </table>
        </div>
	{% else %}
		<p>ไม่พบข้อมูล</p>
    {% endif %}
	<a class="button" href={% url 'buswait:index' %}>back</a>
{% endblock %}

buswait/templates/buswait/index.html
{% extends 'buswait/base.html' %}

{% block title %}{% endblock %}

{% block header %}BusWaiting App{% endblock %}

{% block input %}
	<div style="width:60%;
				margin: auto">
		<form style="float:left; width:50%;" class="form-style-9" action={% url 'buswait:busStopDetail' %} method="get">    
        <h2>Location</h2>
            <input style="width: 70%;" list="busStops" name="busStop" autocomplete="off" placeholder="Bus Stop Name" >
			<input type="submit" value="submit">
			<input type="hidden" name="filter">
            <datalist id="busStops">
			{% if busStop_set %}
                {% for busstop in busStop_set %}
                    <option value={{busstop.name}}>
                {% endfor %}
			{% endif %}
            </datalist>      
			{% if user.is_authenticated %}
				<h3> Your Favorite </h3>
				<div class="box">
					{% for list in favorite_busstop %}
						<ul><a href="{% url 'buswait:busStopDetail' %}?busStop={{list.busstop}}&filter=">
						{{list.busstop}}</a></ul>
					{% endfor %}
				</div>
			{% endif %}
        </form>
        <form style="float:right; width:50%;" class="form-style-9" action={% url 'buswait:busDetail' %} method="get">    
            <h2>Bus Number</h2>
            <input style="width: 70%;" list="busNumbers" name="busNumber" autocomplete="off" placeholder="Bus Number">
            <datalist id="busNumbers">
			{% if busStop_set %}
                {% for bus in bus_set %}
                    <option value={{bus.bus_number}}>
                {% endfor %}
			{% endif %}
            </datalist>
            <input type="submit" value="submit">
			{% if user.is_authenticated %}
				<h3> Your Favorite </h3>
				<div class="box">
					{% for list in favorite_bus %}
						<ul><a href="{% url 'buswait:busDetail' %}?busNumber={{list.bus}}">
						{{list.bus}}</a></ul>
					{% endfor %}
				</div>
			{% endif %}
        </form>
{% endblock %}